# Generated by Django 2.1.7 on 2019-05-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='company',
            new_name='bottomsize',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='account',
            name='brasize',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='pantysize',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='topsize',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
